apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
        version: v1
    spec:
      containers:
      - name: sample
        image: myapp:v1
        ports:
        - containerPort: 8000
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: sample
spec:
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
