apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue-sample
  template:
    metadata:
      labels:
        app: blue-sample
        version: v1-blue
        deployment: blue
    spec:
      containers:
      - name: sample
        image: myapp:v1
        ports:
        - containerPort: 8000
        env:
        - name: deployment
          value: blue
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: green-sample
  template:
    metadata:
      labels:
        app: green-sample
        version: v2-green
        deployment: green
    spec:
      containers:
      - name: sample
        image: myapp:v2
        ports:
        - containerPort: 8000
        env:
        - name: deployment
          value: green
  strategy:
    type: Recreate

